# services > es todo lo que va funcionar dentro del contenedor
services:
  api:
    # indicar cuando se debe de reiniciar el contenedor
    restart: always
    # . > significa toda la informacion que se encuentra en esta ubicacion
    build: .
    ports:
      # PUERTO_EXTERNO:PUERTO_INTERNO
      - "8000:8000"
    links:
      # indica el nombre del contenedor que vamos a mapear para que utilice nuestro servicio API
      - my_bd
    volumes:
      - ./notas:/app/notas
      - ./requirements.txt:/app/requirements.txt
    environment:
      - DB_USER=usuario # estas variables la sacamos de las variables del contenedor de postgres (linea 30)
      - DB_PASSWORD=password
      - DB_NAME=notes
      - DB_HOST=my_bd #si queremos utilizar un contenedor en el compose colocamos su nombre
      - DB_PORT=5432
    env_file: # si tenemos un archivo donde guardaremos todas las variables de entorno, en vez de colocarlas en la propiedad environment usamos la propiedad env_file
      - .env
    
    # para ejecutar el comando en ves del Dockerfile se coloca en la propieda command
    # command: python notas/manage.py runserver 0.0.0.0:8000

  my_bd:
    image: postgres:16.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=usuario
      - POSTGRES_DB=notes
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # mongo -> /data/db
      # mysql -> /var/lib/mysql

volumes:
  postgres-data:


